# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/counter7seg.xdc

# Block Designs: bd/counter7seg_design/counter7seg_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==counter7seg_design || ORIG_REF_NAME==counter7seg_design} -quiet] -quiet

# IP: bd/counter7seg_design/ip/counter7seg_design_vio_0_0/counter7seg_design_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==counter7seg_design_vio_0_0 || ORIG_REF_NAME==counter7seg_design_vio_0_0} -quiet] -quiet

# IP: bd/counter7seg_design/ip/counter7seg_design_ila_0_0/counter7seg_design_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==counter7seg_design_ila_0_0 || ORIG_REF_NAME==counter7seg_design_ila_0_0} -quiet] -quiet

# IP: bd/counter7seg_design/ip/counter7seg_design_led_counter_top_0_0/counter7seg_design_led_counter_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==counter7seg_design_led_counter_top_0_0 || ORIG_REF_NAME==counter7seg_design_led_counter_top_0_0} -quiet] -quiet

# XDC: f:/Embedded/Vivado/KMA/led7seg/led7seg.gen/sources_1/bd/counter7seg_design/counter7seg_design_ooc.xdc
